### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by latifa-wakili**

### CODE REVIEW

**Comment by latifa-wakili** [comment]
@S-BLH
this project is also has the same problem whith freecodcomp errors

**Comment by S-BLH** [comment]
✔️ Created a professional Repo
✔️ Correct use of Gitflow
✔️ Commit messages are meaningful
✔️ Setup the linters correctly
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ Created the pull request
✔️ Good PR description
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your design is responsive
keep it up!

**Comment by latifa-wakili** [comment]
@ah-zamir
please review my project

**Review by ahzamir — APPROVED** [review]
### Hi @latifa-wakili 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Add some description to your pull-request
- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
